name: tapasucon
description: "A new Flutter project."

publish_to: 'Ormatrix' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  salomon_bottom_bar: ^3.3.2
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  qr_flutter: ^4.1.0
  flutter_staggered_grid_view:
  intl: ^0.20.2
  shared_preferences: ^2.0.10
  url_launcher: ^6.0.9
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
  http: 1.3.0
  fluttertoast: ^8.2.12
  emoji_picker_flutter: ^4.3.0
 # google_maps_flutter: ^2.6.0

  carousel_slider: ^5.0.0
  datetime_picker_formfield: ^2.0.0
  sqflite: ^2.0.0+4
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  #image gallery
HTTP request failed, statusCode: 404


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.0"
  flutter_native_splash: ^2.4.2
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.2
  animate_do: ^3.0.2
flutter_native_splash:
  color: "#ffffff"
  background_image: "assets/icons/finalbase.png"
  image: "assets/icons/finalbase.png"
  android: true
 # android_gravity: fitXY
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tapasucon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.jpg
    - assets/icons/
    - assets/places/
    - assets/sports/
    - assets/food/
    - assets/sports/cricket.jpg
    - assets/sports/tt.jpg
    - assets/sports/badminton.jpg
    - assets/sports/tennis.jpg